:- module(declarations, []).
:- dynamic game_started/0.        
:- dynamic urutan_pemain/1.         
:- dynamic giliran/1.               
:- dynamic arah/1.                  
:- dynamic tangan/2.                
:- dynamic draw_pile/1.             
:- dynamic discard_pile/1.         
:- dynamic warna_aktif/1.           
:- dynamic pending_draw/1.         